apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaTopic
metadata:
  name: my-topic
  namespace: strimzi-demo
  labels:
      strimzi.io/cluster: my-cluster
spec:
  replicas: 3
  partitions: 3
  config:
    retention.ms: 7200000
    segment.bytes: 104857600
    retention.bytes: 1073741824