apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: prometheus
  name: grafana-config
  namespace: strimzi-demo
data:
  grafana.ini: |
    [dashboards.json]
    enabled = true
    path = /var/lib/grafana/dashboards
    [paths]
    provisioning = /etc/grafana/provisioning
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: prometheus
  name: grafana-dashboard-provider
  namespace: strimzi-demo
data:
  providers.yaml: |
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: false
      options:
        path: /var/lib/grafana/dashboards
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: prometheus
  name: grafana-datasources-provider
  namespace: strimzi-demo
data:
  providers.yaml: |
    apiVersion: 1
    datasources:
    - name: 'prometheus'
      type: prometheus
      access: proxy
      orgId: 1
      url: http://prometheus:9090
      isDefault: true
      editable: false